/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ChildEntities1ObjectPageObjectPage journey");

        opaTest("Navigate to ChildEntities1ObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheRootEntitiesList.onFilterBar().iExecuteSearch();

            Then.onTheRootEntitiesList.onTable().iCheckRows();
            When.onTheRootEntitiesList.onTable().iPressRow(0);

            Then.onTheRootEntitiesObjectPage.iSeeThisPage();
            Then.onTheRootEntitiesObjectPage.onTable({ property: "childEntities1" }).iCheckRows();
            When.onTheRootEntitiesObjectPage.onTable({ property: "childEntities1" }).iPressRow(0);

            Then.onTheChildEntities1ObjectPage.iSeeThisPage();
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheChildEntities1ObjectPage.onHeader().iCheckHeaderFacet({ facetId: "FacetWithPercent" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheChildEntities1ObjectPage.iCheckSection({ section: "grandChildren::LineItem" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});