/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RootEntitiesObjectPageObjectPage journey");

        opaTest("Navigate to RootEntitiesObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheRootEntitiesList.onFilterBar().iExecuteSearch();

            Then.onTheRootEntitiesList.onTable().iCheckRows();
            When.onTheRootEntitiesList.onTable().iPressRow(0);

            Then.onTheRootEntitiesObjectPage.iSeeThisPage();
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheRootEntitiesObjectPage.onHeader().iCheckHeaderFacet({ facetId: "DataPoint::fieldWithPrice" });
            Then.onTheRootEntitiesObjectPage.onHeader().iCheckHeaderFacet({ facetId: "HeaderFacets::1" });
            Then.onTheRootEntitiesObjectPage.onHeader().iCheckHeaderFacet({ facetId: "CollectionFacet1" });
            Then.onTheRootEntitiesObjectPage.onHeader().iCheckHeaderFacet({ facetId: "CollectionFacet2" });
            Then.onTheRootEntitiesObjectPage.onHeader().iCheckHeaderFacet({ facetId: "FieldGroup::plainText" });
            Then.onTheRootEntitiesObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::plainText",
                field: "description",
                targetAnnotation: ""
            });
            Then.onTheRootEntitiesObjectPage.onHeader().iCheckMicroChart("{i18n>lineChart}");
            Then.onTheRootEntitiesObjectPage.onHeader().iCheckMicroChart("{i18n>columnChart}");
            Then.onTheRootEntitiesObjectPage.onHeader().iCheckMicroChart("{i18n>harveyChart}");
            Then.onTheRootEntitiesObjectPage.onHeader().iCheckMicroChart("{i18n>stackedBarChart}");
            Then.onTheRootEntitiesObjectPage.onHeader().iCheckMicroChart("{i18n>comparisonChart}");
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheRootEntitiesObjectPage.iCheckNumberOfSections(7);
            When.onTheRootEntitiesObjectPage.iPressSectionIconTabFilterButton("collectionFacetSection");
            Then.onTheRootEntitiesObjectPage.iCheckSection({ section: "collectionFacetSection" });
            When.onTheRootEntitiesObjectPage.iPressSectionIconTabFilterButton("FieldGroup::ShowWhenInEdit");
            Then.onTheRootEntitiesObjectPage.iCheckSection({ section: "FieldGroup::ShowWhenInEdit" });
            When.onTheRootEntitiesObjectPage.iPressSectionIconTabFilterButton("chartDataCollection");
            Then.onTheRootEntitiesObjectPage.iCheckSection({ section: "chartDataCollection" });
            When.onTheRootEntitiesObjectPage.iPressSectionIconTabFilterButton("childEntities1Section");
            Then.onTheRootEntitiesObjectPage.iCheckSection({ section: "childEntities1Section" });
            When.onTheRootEntitiesObjectPage.iPressSectionIconTabFilterButton("association2one::FieldGroup::data");
            Then.onTheRootEntitiesObjectPage.iCheckSection({ section: "association2one::FieldGroup::data" });
            When.onTheRootEntitiesObjectPage.iPressSectionIconTabFilterButton("childEntities3::LineItem");
            Then.onTheRootEntitiesObjectPage.iCheckSection({ section: "childEntities3::LineItem" });
            When.onTheRootEntitiesObjectPage.iPressSectionIconTabFilterButton("chartEntities::Chart");
            Then.onTheRootEntitiesObjectPage.iCheckSection({ section: "chartEntities::Chart" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});