/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RootEntitiesListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheRootEntitiesList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheRootEntitiesList.onFilterBar().iCheckFilterField("{i18n>semanticKeyField}");
            Then.onTheRootEntitiesList.onFilterBar().iCheckFilterField("{i18n>date}");
            Then.onTheRootEntitiesList.onFilterBar().iCheckFilterField("{i18n>criticality}");
            Then.onTheRootEntitiesList.onFilterBar().iCheckFilterField("{i18n>OrganizationalUnit}");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheRootEntitiesList.onTable().iCheckColumns(17, {"3":{"header":"{i18n>fieldWithToolTip}"},"7":{"header":"{i18n>progressIndicator}"},"8":{"header":"{i18n>ratingIndicator}"},"9":{"header":"{i18n>bulletChart}"},"11":{"header":"{i18n>adminData}"},"12":{"header":"{i18n>radialChart}"},"13":{"header":"{i18n>contactQuickView}"},"14":{"header":"{i18n>changeProgress}"},"15":{"header":"{i18n>IntentBasedNavigation}"},"imageUrl":{"header":"{i18n>image}"},"stringProperty":{"header":"{i18n>semanticKeyField}"},"fieldWithPrice":{"header":"{i18n>fieldWithPrice}"},"fieldWithUoM":{"header":"{i18n>fieldWithUoM}"},"association2one/country_code":{"header":"Navigation field only available via settings"},"fieldWithCriticality":{"header":"{i18n>fieldWithCriticality}"},"association2one_ID":{"header":"{i18n>Order}"},"fieldWithURLtext":{"header":"{i18n>dataFieldWithURL}"}});

        });


        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheRootEntitiesList.onFilterBar().iExecuteSearch();
            
            Then.onTheRootEntitiesList.onTable().iCheckRows();

            When.onTheRootEntitiesList.onTable().iPressRow(0);
            Then.onTheRootEntitiesObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});